version: "3.7"
services:
  # servicio 1: La base de datos
  serv-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyectofinal
      MYSQL_USER: root
      MYSQL_PASSWORD: userfull
    ports:
      # puerto externo: puerto interno
      - 3306:3306
    volumes:
      - ./databases/mysql_3.7/schemas:/var/lib/mysql
    networks:
      laravel_prod_net:
        ipv4_address: 173.22.100.9

  # servicio 2: La instalación de apache
  serv-laravel:
    build:
      # context: de donde se va a recuperar la configuración para la instalación
      context: ./
      dockerfile: dockerfile
    ports:
      - 8200:80
    volumes:
      - ./SemestralProyectos:/var/www/
      - ./SemestralProyectos/public:/var/www/html
    networks:
      laravel_prod_net:
        ipv4_address: 173.22.100.10
    # depends_on indica que se cree primero la bd (servicio 1)
    depends_on:
      - serv-mysql

# se confirman los volumenes
volumes:
  SemestralProyectos:  # carpeta ./example-prod
  databases:      # carpeta E:/projects/docker/databases/mysql_3.7/schemas
networks:
  laravel_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.22.100.0/24
